apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-169405952
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-169405952
    app.kubernetes.io/part-of: test-app-169405952
  name: go-169405952
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-169405952
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-169405952
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/redhat-user-workloads-stage/skhileri-tenant/test-app-169405952/go-169405952@sha256:b708797d099e1ff25e77145cbdcec6d536250f113cb50d44d6066715aa7d3a59
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
